### ISSUE TITLE
Integrating bevy_input back to the crate

### ISSUE THREAD

**Issue by StepanTheGreat** [StepanTheGreat/quadify#7]
This should be a simple integration of `bevy_input` back to `quadify` as it was in the first version of the crate.

**Comment by sokorototo** [comment]
Isn't this complete?

**Comment by StepanTheGreat** [comment]
I guess not completely, though for now most is done, so I'm closing this. **for now**

**Comment by sokorototo** [comment]
> I guess not completely, though for now most is done, so I'm closing this. **for now**

What hasn't been completed?
